# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  platformUrl: 'https://demolabs.42crunch.cloud'
  platformService: 'services.demolabs.42crunch.cloud:8001'
  github_org_name: heshaam-42c
  github_repo_name: VAmPI
  github_branch_name: master
  
steps:
# - checkout: self
# - checkout: protections
- task: NodeTool@0
  displayName: Use Node 12 or higher
  inputs:
    versionSpec: '=12.0.0'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10' 
    addToPath: true 
    #architecture: 'x64' # Options: x86, x64 (this argument applies only on Windows agents)

# Install Docker
- task: DockerInstaller@0
  displayName: 'Install Docker'
  
- script: python -m pip install requests --upgrade pip
  displayName: 'Install tools'

# Connect to Azure
- task: AzureCLI@2
  inputs:
    azureSubscription: 'platform-demos-apis-hesh'  # Use the name of the service connection created earlier
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show
      az group list

- script: |
    az apim api export -g customer-pocs -n api-42c-demo --api-id photomanager --export-format OpenApiJsonFile --file-path $(Build.Repository.LocalPath)
    pwd
    ls -la

# 42Crunch API Security Audit
# - task: APIContractSecurityAudit@3
#   displayName: Auditing OAS Files
#   inputs:
#     apiToken: '$(42C_API_TOKEN)'
#     minScore: '75'
#     platformUrl: '$(platformUrl)'
#     logLevel: DEBUG
#     defaultCollectionName: 'AzureDevOps heshaam-42c/VAmPI--master'
#     ignoreFailures: 'true'
#     sarifReport: 'audit-report-$(Build.BuildId).sarif'

# 42Crunch Freemium API Security Audit
- task: APISecurityAuditFreemium@1
  inputs:
    enforceSQG: false
    logLevel: DEBUG
    sarifReport: '$(Build.Repository.LocalPath)/$(Build.BuildId)-auditreport.sarif'
    exportAsPDF: '$(Build.Repository.LocalPath)/$(Build.BuildId)-auditreport.pdf'

# Publish SARIF Artifact
- task: PublishBuildArtifacts@1
  displayName: 'publishAuditSarif'
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)/$(Build.BuildId)-auditreport.sarif'
    ArtifactName: 'CodeAnalysisLogs'
    publishLocation: 'Container'

# Compress & Base64 encode the sarif file
- script: |
    sarif_file_base64=$(gzip -c $(Build.Repository.LocalPath)/$(Build.BuildId)-auditreport.sarif | base64 -w0)
    echo "##vso[task.setvariable variable=AUDIT_SARIF_FILE]$sarif_file_base64"
  displayName: 'Compress & Base64 encode sarif file'

# Upload SARIF report to GitHub Advanced Security (GHAS)
- task: Bash@3
  displayName: 'Upload SARIF report to GitHub Advanced Security (GHAS)'
  inputs:
    targetType: 'inline'
    script: |
      echo "Uploading SARIF report to GitHub Advanced Security (GHAS)"
      echo "Request body: {\"commit_sha\":\"$(Build.SourceVersion)\",\"ref\":\"refs/heads/$(github_branch_name)\",\"sarif\":\"$(AUDIT_SARIF_FILE)\"}"
      curl -L \
      -H "Authorization: Bearer $(GITHUB_TOKEN)" \
      -H "Accept: application/vnd.github.v3+json" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      https://api.github.com/repos/$(github_org_name)/$(github_repo_name)/code-scanning/sarifs \
      -d '{"commit_sha":"$(Build.SourceVersion)","ref":"refs/heads/$(github_branch_name)","sarif":"$(AUDIT_SARIF_FILE)"}'