# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow locates REST API file contracts
# (Swagger or OpenAPI format, v2 and v3, JSON and YAML)
# and runs 300+ security checks on them using 42Crunch Security Audit technology.
#
# Documentation is located here: https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a free 42Crunch account at https://platform.42crunch.com/register
#
# 2. Follow steps at https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
#    to create an API Token on the 42Crunch platform
#
# 3. Add a secret in GitHub as explained in https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm,
#    store the 42Crunch API Token in that secret, and supply the secret's name as api-token parameter in this workflow
#
# If you have any questions or need help contact https://support.42crunch.com

name: "42crunch"

# follow standard Code Scanning triggers
on: 
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  PLATFORM_URL: https://demolabs.42crunch.cloud
  PLATFORM_SERVICE_ENDPOINT: services.demolabs.42crunch.cloud:8001
  TOKEN_ENV_VAR: ACCESS_TOKEN

permissions:
  contents: read

jobs:
  run_42c_audit:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for 42Crunch/api-security-audit-action to upload results to Github Code Scanning
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: 42crunch-static-api-testing
        uses: 42crunch/api-security-audit-action@v3
        with:
          api-token: ${{ secrets.API_TOKEN }}
          platform-url: ${{ env.PLATFORM_URL}}
          default-collection-name: GitHubActions heshaam-42c/VAmPI--${{ github.ref_name }}
          # Upload results to Github code scanning
          upload-to-code-scanning: true
          log-level: debug
          json-report: audit-action-report-${{ github.run_id }}
          sarif-report: 42c-audit-report-${{ github.run_id }}.sarif
          ignore-failures: true
      - name: save-audit-report
        if: always()        
        uses: actions/upload-artifact@v4
        with:
          name: auditaction-report-${{ github.run_id }}
          path: audit-action-report-${{ github.run_id }}.json
          if-no-files-found: error
      - name: save-audit-sarif-report
        if: always()        
        uses: actions/upload-artifact@v4
        with:
          name: 42c-audit-sarif-report-${{ github.run_id }}
          path: 42c-audit-report-${{ github.run_id }}.sarif
          if-no-files-found: warn

  # We use the output of the previous step to scan the APIs       
  run_42c_scan:
    runs-on: ubuntu-latest
    needs: run_42c_audit
    permissions:        
      contents: read # for actions/checkout to fetch code
      security-events: write # for 42Crunch/api-security-audit-action to upload results to Github Code Scanning
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy API
        run: |
          docker compose up -d
      - name: download_audit_report    
        uses: actions/download-artifact@v4
        with:
          name: auditaction-report-${{ github.run_id }}  
      - name: get vampi api id
        id: get_vampi_api_id
        run: |
          apiId=$(cat ./audit-action-report-${{ github.run_id }}.json | jq -r '.audit.report.${{ vars.VAMPI_OAS_PATH }}.apiId')
          echo "VAMPI_API_UUID=$apiId" >> $GITHUB_OUTPUT
          cat audit-action-report-${{ github.run_id }}.json
      # Scan V2
      - name: get_vampi_scan_alias
        id: parse_alias
        run: |
          aliasId=$(cat ./.42c/conf.yaml | yq '.apis.${{ vars.VAMPI_OAS_PATH }}.alias')
          echo $aliasId
          echo "VAMPI_SCAN_ALIAS=$aliasId" >> $GITHUB_OUTPUT
      - name: upload_v2_scan_config
        id: upload_v2_scan_config
        run: | 
            scanconfig_response=$(python3 .42c/scripts/conformance_scanv2.py -c ${{ secrets.API_TOKEN }} -p ${{env.PLATFORM_URL}} -a ${{steps.get_vampi_api_id.outputs.VAMPI_API_UUID}} -n github-actions -t scan_token.json -f .42c/scan/${{steps.parse_alias.outputs.VAMPI_SCAN_ALIAS}}/scanconf.json --action upload_conf)
            scan_token=$(cat scan_token.json | jq -r '.scan_token')
            echo "SCANV2_TOKEN=$scan_token" >> $GITHUB_OUTPUT
      - name: vampi api login
        run: |
          vampiResponse=$(curl -X POST -H "Content-Type: application/json" -d '{"username":"name1","password":"pass1"}' http://host.docker.internal:5002/users/v1/login)
          echo $vampiResponse
      - name: 42crunch-dynamic-api-testing
        run: |
            docker pull 42crunch/scand-agent:v2
            docker run -e SCAN_TOKEN=${{ steps.upload_v2_scan_config.outputs.SCANV2_TOKEN }} -e SCAN42C_HOST=http://host.docker.internal:5002 -e PLATFORM_SERVICE=${{ env.PLATFORM_SERVICE_ENDPOINT }} 42crunch/scand-agent:v2
            echo "Scan report: ${{ env.PLATFORM_URL }}/apis/${{steps.get_vampi_api_id.outputs.VAMPI_API_UUID}}/scan"